config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  resources :roadmaps do
    post "copy", on: :member
  end
  devise_for :users
  get "profile", to: "users#profile"
  resources :roadmap_steps do
    patch :move_up,   on: :member
    patch :move_down, on: :member
    resources :step_completions, only: [ :create, :destroy ]
  end
  resources :focus_sessions
  root "roadmaps#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom shadow-sm">
  <div class="container">
    <%= link_to "📘 Roadmaps", root_path, class: "navbar-brand text-primary fw-bold" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "🏠 StepWiz", root_path, class: "nav-link text-primary" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-primary" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            📌 Roadmaps
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Roadmaps", roadmaps_path, class: "dropdown-item" %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Create New Roadmap", new_roadmap_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "✏️ Edit Profile", edit_user_registration_path, class: "nav-link text-primary" %>
          </li>
           <li class="nav-item">
                <%= link_to "👤 Profile", profile_path(current_user), class: "nav-link" %>
           </li>

          <li class="nav-item">
            <%= button_to "🚪 Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger ms-2", form_class: "d-inline" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "🔐 Login", user_session_path, class: "nav-link text-primary" %>
          </li>
          <li class="nav-item">
            <%= link_to "📝 Signup", new_user_registration_path, class: "nav-link text-success fw-semibold" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>